theme = "tokyonight"

[keys.insert]
C-s = ["normal_mode", "commit_undo_checkpoint", ":write"]

[keys.normal]
X = "extend_line_above"
C-s = ["normal_mode", "commit_undo_checkpoint", ":write"] 
C-j = ["goto_next_paragraph"]
C-k = ["goto_prev_paragraph"]
C-a = []
C-e = ["increment"]
C-x = [":buffer-close"] # used to be decrement
C-r = ["decrement"]
C-X = [":buffer-close-others"]
C-n = "@/[0-9]<ret>"
C-h = "jump_view_left"
C-l = "jump_view_right"
C-H = "swap_view_left"
C-L = "swap_view_right"
A-m = "flip_selections"

[keys.select]
X = "select_line_above"
C-j = ["goto_next_paragraph"]
C-k = ["goto_prev_paragraph"]
";" = ["collapse_selection", "normal_mode"]

[editor]
line-number = "relative"
mouse = false
bufferline = "never"
end-of-line-diagnostics = "hint"
gutters = ["diagnostics", "line-numbers", "spacer"]

[editor.inline-diagnostics]
cursor-line = "error"

[editor.soft-wrap]
enable = true
